version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: seguros
      POSTGRES_PASSWORD: T3@tbycCM2Unz
      POSTGRES_DB: seguros
    ports:
      - "6432:5432"

  redis:
    image: redis
    volumes:
      - redis_data:/data

  django:
    build: .
    volumes:
      - static:/seguros/seguros/seguros/static
      - media:/seguros/seguros/seguros/media
    environment:
      SEGUROS_SUPERUSER_PASSWORD: "contraseñita"
      SEGUROS_SUPERUSER_EMAIL: "example@example.com"
      SEGUROS_SUPERUSER_USERNAME: "organizame.admin"
      DEBUG: 1
      SECRET_KEY: k$^m!=dp7ah&0_(9&0!b(47thue*@2x)u=883w3)1*pt8ae(i=
      SEGUROS_ALLOWED_HOSTS: localhost
      SEGUROS_CSRF_TRUSTED_ORIGINS: "http://localhost:1337,http://127.0.0.1:1337"
      SEGUROS_SQL_ENGINE: django.db.backends.postgresql
      SEGUROS_SQL_DATABASE: seguros
      SEGUROS_SQL_USER: seguros
      SEGUROS_SQL_PASSWORD: T3@tbycCM2Unz
      SEGUROS_SQL_HOST: db
      SEGUROS_SQL_PORT: 5432
      SEGUROS_REDIS: "redis://redis:6379"
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  nginx:    
    build: ./nginx
    volumes:
      - static:/web/static
      - media:/web/media
    ports:
      - "1337:80"
    depends_on:
      - django


volumes:
  postgres_data:
  redis_data:
  static:
  media:

networks:
  default:
    name: seguros-network

