services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: seguros
      POSTGRES_PASSWORD: T3@tbycCM2Unz
      POSTGRES_DB: seguros
    ports:
      - "6432:5432"
    networks:
      - proxy

  redis:
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - proxy

  django:
    build: .
    volumes:
      - static:/seguros/seguros/seguros/static
      - media:/seguros/seguros/seguros/media
    environment:
      SEGUROS_SUPERUSER_PASSWORD: "contraseñita"
      SEGUROS_SUPERUSER_EMAIL: "example@example.com"
      SEGUROS_SUPERUSER_USERNAME: "organizame.admin"
      DEBUG: 1
      SECRET_KEY: k$^m!=dp7ah&0_(9&0!b(47thue*@2x)u=883w3)1*pt8ae(i=
      SEGUROS_ALLOWED_HOSTS: localhost
      SEGUROS_CSRF_TRUSTED_ORIGINS: "http://localhost:1337,http://127.0.0.1:1337"
      SEGUROS_SQL_ENGINE: django.db.backends.postgresql
      SEGUROS_SQL_DATABASE: seguros
      SEGUROS_SQL_USER: seguros
      SEGUROS_SQL_PASSWORD: T3@tbycCM2Unz
      SEGUROS_SQL_HOST: db
      SEGUROS_SQL_PORT: 5432
      SEGUROS_REDIS: "redis://redis:6379"
      EMAIL_HOST_USER: "elmonjeamarillo@gmail.com"
      EMAIL_HOST_PASSWORD: "gzrlntcjrufjnvdt"
      EMAIL_DEAFULT_FROM: "elmonjeamarillo@gmail.com"
      MAX_FILE_SIZE_MB: 1
      RUL_ASU_BET: "_DVWRoqmwRLj-ywo5h0eD0QqaQJeL2ZzQ5hPqQMwX3U="
      ALLOWED_FILE_TYPES: "application/pdf,image/jpeg,image/png,image/webp"
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - proxy

  nginx:    
    build: ./nginx
    volumes:
      - static:/web/static
      - media:/web/media
    ports:
      - "443:443"
    depends_on:
      - django
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seguros.rule=Host(`seguros.rulo-desarrollo.cfd`)"
      - "traefik.http.routers.seguros.entrypoints=websecure"
      - "traefik.http.routers.seguros.tls.certresolver=myresolver"



volumes:
  postgres_data:
  redis_data:
  static:
  media:

networks:
  proxy:
    external: true 


