# Generated by Django 4.2.10 on 2024-03-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmpresaContratante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=20)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("activo", models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=20)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parentesco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
                ("activo", models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonaPrincipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=20)),
                ("primer_apellido", models.CharField(max_length=20)),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "lugar_nacimiento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("feccha_nacimiento", models.DateTimeField()),
                (
                    "genero",
                    models.CharField(
                        choices=[("H", "Hombre"), ("M", "Mujer"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("estatus", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Planes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=20)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("activo", models.IntegerField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.empresacontratante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Poliza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=20)),
                ("numero_poliza", models.PositiveSmallIntegerField()),
                ("fechavigencia", models.DateTimeField()),
                ("estatus", models.CharField(max_length=10)),
                (
                    "forma_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.formapago",
                    ),
                ),
                (
                    "persona_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.personaprincipal",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.planes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoConductoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=20)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoMediocontacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=20)),
                ("activo", models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=20)),
                ("descripcion", models.CharField(max_length=50)),
                ("activo", models.IntegerField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Siniestros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_siniestro",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "descripcion_siniestro",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("fecha_evento", models.DateTimeField()),
                ("estatus", models.CharField(max_length=10)),
                (
                    "poliza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.poliza",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="poliza",
            name="tipo_conducto_pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="documentos.tipoconductopago",
            ),
        ),
        migrations.CreateModel(
            name="PlanDocumentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=20)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.documentos",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.empresacontratante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonaRelacionada",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("clave", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=50)),
                ("primer_apellido", models.CharField(max_length=50)),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("H", "Hombre"), ("M", "Mujer"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("estatus", models.CharField(max_length=10)),
                (
                    "persona_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.personaprincipal",
                    ),
                ),
                (
                    "tipo_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.tipopersona",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="tipo_persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documentos.tipopersona"
            ),
        ),
        migrations.CreateModel(
            name="CheckDocumentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_poliza", models.PositiveSmallIntegerField()),
                ("plan", models.CharField(max_length=20)),
                (
                    "necesario",
                    models.CharField(
                        choices=[("S", "Si"), ("N", "No"), ("I", "Incompleto")],
                        max_length=1,
                    ),
                ),
                (
                    "entregado",
                    models.CharField(
                        choices=[("S", "Si"), ("N", "No"), ("I", "Incompleto")],
                        max_length=1,
                    ),
                ),
                ("archivo", models.FileField(upload_to="")),
                ("fecha_adjuntado", models.DateTimeField()),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.documentos",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.empresacontratante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beneficiarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_poliza", models.PositiveSmallIntegerField()),
                (
                    "porcentaje_participacion",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "persona_relacionada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.personarelacionada",
                    ),
                ),
                (
                    "tipo_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.tipopersona",
                    ),
                ),
            ],
        ),
    ]
