# Generated by Django 4.2.10 on 2024-03-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personaprincipal",
            old_name="feccha_nacimiento",
            new_name="fecha_nacimiento",
        ),
        migrations.AlterField(
            model_name="beneficiarios",
            name="numero_poliza",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documentos.poliza"
            ),
        ),
        migrations.AlterField(
            model_name="checkdocumentos",
            name="numero_poliza",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="documentos.poliza"
            ),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="nombre",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="primer_apellido",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="segundo_apellido",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="personarelacionada",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="personarelacionada",
            name="nombre",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="personarelacionada",
            name="primer_apellido",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="personarelacionada",
            name="segundo_apellido",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="documentos.empresacontratante",
            ),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="numero_poliza",
            field=models.CharField(max_length=25),
        ),
    ]
