# Generated by Django 4.2.10 on 2024-03-03 23:01

from django.db import migrations, models
import documentos.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documentos",
            "0005_historicaltipopersona_historicaltipomediocontacto_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentos",
            name="clave",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="empresacontratante",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="formapago",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="historicaldocumentos",
            name="clave",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalempresacontratante",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalformapago",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalparentesco",
            name="descripcion",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="historicalpersonaprincipal",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonarelacionada",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalplandocumentos",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalplanes",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltipoconductopago",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltipomediocontacto",
            name="descripcion",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="historicaltipopersona",
            name="clave",
            field=documentos.models.ClaveField(
                db_index=True, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="parentesco",
            name="descripcion",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="personarelacionada",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="plandocumentos",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="planes",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="tipoconductopago",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="tipomediocontacto",
            name="descripcion",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="tipopersona",
            name="clave",
            field=documentos.models.ClaveField(max_length=20, unique=True),
        ),
    ]
