# Generated by Django 4.2.10 on 2024-03-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0006_alter_documentos_clave_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonaprincipal",
            name="asesor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="documentos.asesor",
            ),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="asesor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="documentos.asesor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="empresacontratante",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicalempresacontratante",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
