# Generated by Django 4.2.10 on 2024-03-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sepomex", "0006_remove_asentamiento_asentamiento_cp_idx_and_more"),
        ("documentos", "0007_historicalpersonaprincipal_asesor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonaprincipal",
            name="asentamiento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sepomex.asentamiento",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonaprincipal",
            name="calle",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalpersonaprincipal",
            name="estado",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sepomex.estado",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonaprincipal",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sepomex.municipio",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonaprincipal",
            name="numero",
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="historicalpersonaprincipal",
            name="piso",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="asentamiento",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sepomex.asentamiento",
            ),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="calle",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="estado",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sepomex.estado",
            ),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="municipio",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sepomex.municipio",
            ),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="numero",
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="piso",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
