# Generated by Django 4.2.10 on 2024-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0008_historicalpersonaprincipal_asentamiento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalasesorempresa",
            name="asesor",
        ),
        migrations.RemoveField(
            model_name="historicalasesorempresa",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="historicalasesorempresa",
            name="history_user",
        ),
        migrations.AddField(
            model_name="asesor",
            name="empresa",
            field=models.ManyToManyField(to="documentos.empresacontratante"),
        ),
        migrations.DeleteModel(
            name="AsesorEmpresa",
        ),
        migrations.DeleteModel(
            name="HistoricalAsesorEmpresa",
        ),
    ]
