# Generated by Django 4.2.10 on 2024-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0010_remove_historicalbeneficiarios_history_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaprincipal",
            name="piso",
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="numero_interior",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
