# Generated by Django 4.2.10 on 2024-03-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0011_remove_personaprincipal_piso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsesorEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo_empleado", models.EmailField(max_length=254)),
                ("codigo_empleado", models.CharField(max_length=50)),
                (
                    "asesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.asesor",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.empresacontratante",
                    ),
                ),
            ],
        ),
    ]
