# Generated by Django 4.2.10 on 2024-03-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0012_asesorempresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asesor",
            name="telefono1",
        ),
        migrations.RemoveField(
            model_name="asesor",
            name="telefono2",
        ),
        migrations.RemoveField(
            model_name="personaprincipal",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="personaprincipal",
            name="municipio",
        ),
        migrations.AddField(
            model_name="asesorempresa",
            name="telefono",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name="asesor",
            name="empresa",
        ),
    ]
