# Generated by Django 4.2.10 on 2024-03-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0013_remove_asesor_telefono1_remove_asesor_telefono2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asesor",
            name="empresa",
            field=models.ManyToManyField(
                through="documentos.AsesorEmpresa", to="documentos.empresacontratante"
            ),
        ),
    ]
