# Generated by Django 4.2.10 on 2024-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0014_remove_asesor_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asesor",
            name="empresa",
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="fecha_nacimiento",
            field=models.DateField(),
        ),
    ]
