# Generated by Django 4.2.10 on 2024-04-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0016_asesor_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiarios",
            name="persona_relacionada",
        ),
        migrations.AddField(
            model_name="beneficiarios",
            name="nombre_completo",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="correo",
            field=models.EmailField(default="correo@empresa.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="asesorempresa",
            name="telefono",
            field=models.CharField(default="telefono", max_length=20),
        ),
        migrations.AlterField(
            model_name="beneficiarios",
            name="porcentaje_participacion",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
