# Generated by Django 4.2.10 on 2024-04-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0017_remove_beneficiarios_persona_relacionada_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poliza",
            old_name="fechavigencia",
            new_name="fecha_vigencia",
        ),
        migrations.AddField(
            model_name="personaprincipal",
            name="telefono",
            field=models.CharField(default="NA", max_length=100),
        ),
        migrations.AddField(
            model_name="poliza",
            name="fecha_emision",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="poliza",
            name="fecha_pago",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
