# Generated by Django 4.2.10 on 2024-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0019_alter_asesorempresa_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaprincipal",
            name="correo",
            field=models.EmailField(
                blank=True, default="correo@empresa.com", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="telefono",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="fecha_emision",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="fecha_pago",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="poliza",
            name="fecha_vigencia",
            field=models.DateField(),
        ),
    ]
