# Generated by Django 4.2.10 on 2024-04-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0020_alter_personaprincipal_correo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaprincipal",
            name="estatus",
            field=models.CharField(
                choices=[("A", "ACTIVO"), ("I", "INACTIVO")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="personarelacionada",
            name="estatus",
            field=models.CharField(
                choices=[("A", "ACTIVO"), ("I", "INACTIVO")], max_length=10
            ),
        ),
    ]
