# Generated by Django 4.2.10 on 2024-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0021_alter_personaprincipal_estatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poliza",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("PGD", "PAGADO"),
                    ("PEN", "PEDIENTE DE PAGO"),
                    ("EPR", "EN PROCESO"),
                ],
                max_length=10,
            ),
        ),
    ]
