# Generated by Django 4.2.10 on 2024-04-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0022_alter_poliza_estatus"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="poliza",
            unique_together={("empresa", "numero_poliza")},
        ),
    ]
