# Generated by Django 4.2.10 on 2024-05-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0025_alter_beneficiarios_nombre_completo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personaprincipal",
            old_name="estatus",
            new_name="estatus_persona",
        ),
        migrations.RenameField(
            model_name="personarelacionada",
            old_name="estatus",
            new_name="estatus_persona",
        ),
    ]
