# Generated by Django 4.2.10 on 2024-05-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0026_rename_estatus_personaprincipal_estatus_persona_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personaprincipal",
            old_name="asesor",
            new_name="asesor_cliente",
        ),
        migrations.RenameField(
            model_name="poliza",
            old_name="asesor",
            new_name="asesor_poliza",
        ),
    ]
