# Generated by Django 4.2.10 on 2024-05-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0027_rename_asesor_personaprincipal_asesor_cliente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiarios",
            name="tipo_persona",
        ),
        migrations.AddField(
            model_name="beneficiarios",
            name="parentesco",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="documentos.parentesco",
            ),
        ),
    ]
