# Generated by Django 4.2.10 on 2024-05-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0028_remove_beneficiarios_tipo_persona_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiarios",
            name="parentesco",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documentos.parentesco",
            ),
        ),
    ]
