# Generated by Django 4.2.10 on 2024-05-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documentos",
            "0030_remove_plandocumentos_clave_planes_gastos_medicos_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="empresacontratante",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empresacontratante",
            name="logo_small",
            field=models.ImageField(blank=True, null=True, upload_to="empresa"),
        ),
        migrations.AlterField(
            model_name="empresacontratante",
            name="pleca",
            field=models.ImageField(blank=True, null=True, upload_to="empresa"),
        ),
    ]
