# Generated by Django 4.2.10 on 2024-05-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0031_empresacontratante_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresacontratante",
            name="pleca",
        ),
    ]
