# Generated by Django 4.2.10 on 2024-05-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0032_remove_empresacontratante_pleca"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentosSiniestros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "siniestro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.siniestros",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="plandocumentos",
            name="documento",
        ),
        migrations.RemoveField(
            model_name="plandocumentos",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="documentos",
            name="clave",
        ),
        migrations.AddField(
            model_name="documentos",
            name="poliza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="documentos.poliza",
            ),
        ),
        migrations.DeleteModel(
            name="CheckDocumentos",
        ),
        migrations.DeleteModel(
            name="PlanDocumentos",
        ),
    ]
