# Generated by Django 4.2.10 on 2024-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documentos",
            "0033_documentossiniestros_remove_plandocumentos_documento_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentos",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="documento_poliza/"
            ),
        ),
        migrations.AddField(
            model_name="documentossiniestros",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="documento_siniestro/"
            ),
        ),
    ]
