# Generated by Django 4.2.10 on 2024-05-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0034_documentos_archivo_documentossiniestros_archivo"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentos",
            unique_together={("poliza", "descripcion")},
        ),
        migrations.AlterUniqueTogether(
            name="documentossiniestros",
            unique_together={("siniestro", "descripcion")},
        ),
    ]
