# Generated by Django 4.2.10 on 2024-05-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0035_alter_documentos_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siniestros",
            name="fecha_evento",
            field=models.DateField(),
        ),
    ]
