# Generated by Django 4.2.10 on 2024-05-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0036_alter_siniestros_fecha_evento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siniestros",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("PGD", "PAGADO"),
                    ("PEN", "PEDIENTE DE PAGO"),
                    ("EPR", "EN PROCESO"),
                ],
                max_length=10,
            ),
        ),
    ]
