# Generated by Django 4.2.10 on 2024-06-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0037_alter_siniestros_estatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaprincipal",
            name="curp",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="personarelacionada",
            name="curp",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="personaprincipal",
            unique_together={("asesor_cliente", "curp")},
        ),
    ]
