# Generated by Django 4.2.10 on 2024-06-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0038_alter_personaprincipal_curp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaprincipal",
            name="tipo_persona",
        ),
        migrations.RemoveField(
            model_name="personarelacionada",
            name="tipo_persona",
        ),
    ]
