# Generated by Django 4.2.10 on 2024-06-27 15:57

from django.db import migrations
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0039_remove_personaprincipal_tipo_persona_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentossiniestros",
            name="archivo",
            field=documentos.models.EncryptedFileField(
                blank=True, null=True, upload_to="documento_siniestro/"
            ),
        ),
    ]
