# Generated by Django 4.2.10 on 2024-07-02 22:59

from django.db import migrations, models
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0040_alter_documentossiniestros_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentos",
            name="archivo",
            field=documentos.models.EncryptedFileField(
                blank=True, null=True, upload_to="documento_poliza/"
            ),
        ),
        migrations.CreateModel(
            name="TipoDocumentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("P", "POLIZA"), ("S", "SINIESTRO")], max_length=2
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("tipo", "descripcion")},
            },
        ),
    ]
