# Generated by Django 4.2.10 on 2024-07-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0041_alter_documentos_archivo_tipodocumentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="poliza",
            name="monto",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Importe"
            ),
        ),
    ]
