# Generated by Django 4.2.10 on 2024-07-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0042_poliza_monto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planes",
            old_name="gastos_medicos",
            new_name="gastosMedicos",
        ),
    ]
