# Generated by Django 4.2.10 on 2024-08-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0043_rename_gastos_medicos_planes_gastosmedicos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poliza",
            old_name="monto",
            new_name="monto_pago",
        ),
        migrations.AddField(
            model_name="beneficiarios",
            name="curp",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="empresacontratante",
            name="link_pago",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="poliza",
            name="renovacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="poliza",
            name="suma_asegurada",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="poliza",
            name="unidad_pago",
            field=models.CharField(
                blank=True,
                choices=[("UDI", "UDIS"), ("PE", "PESO"), ("DO", "DOLAR")],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="empresacontratante",
            name="link",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="numero",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="numero_interior",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
