# Generated by Django 4.2.10 on 2024-08-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documentos",
            "0044_rename_monto_poliza_monto_pago_beneficiarios_curp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="poliza",
            name="periodo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "MENSUAL"),
                    ("T", "TRIMESTRAL"),
                    ("S", "SEMESTRAL"),
                    ("A", "ANUAL"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="beneficiarios",
            name="curp",
            field=models.CharField(
                blank=True, default=None, max_length=20, null=True, verbose_name="CURP"
            ),
        ),
        migrations.AlterField(
            model_name="personaprincipal",
            name="numero",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="Numero Exterior",
            ),
        ),
    ]
