# Generated by Django 4.2.10 on 2024-08-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0045_poliza_periodo_alter_beneficiarios_curp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planes",
            name="clave",
        ),
    ]
