# Generated by Django 4.2.10 on 2024-10-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0047_alter_poliza_estatus_alter_siniestros_estatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonaRelacionada",
        ),
    ]
