# Generated by Django 4.1.3 on 2023-04-09 17:15

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="parametros_colores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elemento", models.CharField(db_column="elemento", max_length=50)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
            options={
                "db_table": "parametros_colores",
            },
        ),
        migrations.CreateModel(
            name="parametros_imagenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=60)),
                ("image", models.ImageField(upload_to="images_parameter")),
            ],
        ),
    ]
