# Generated by Django 4.2.10 on 2024-03-01 15:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tema", "0002_alter_parametros_colores_elemento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametros_colores",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
