# Generated by Django 4.2.10 on 2024-10-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tema", "0006_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
