# Generated by Django 4.2.10 on 2024-03-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=2, unique=True)),
                ("nombre", models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoAsentamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=2, unique=True)),
                ("nombre", models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=4)),
                ("nombre", models.CharField(max_length=250)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sepomex.estado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asentamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_postal", models.CharField(max_length=5)),
                ("nombre", models.CharField(max_length=5000)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sepomex.municipio",
                    ),
                ),
                (
                    "tipo_asentamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sepomex.tipoasentamiento",
                    ),
                ),
            ],
        ),
    ]
