# Generated by Django 4.2.10 on 2024-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sepomex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estado",
            name="clave",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="clave",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="tipoasentamiento",
            name="clave",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
