# Generated by Django 4.2.10 on 2024-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sepomex", "0002_alter_estado_clave_alter_municipio_clave_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estado",
            name="clave",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="clave",
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="tipoasentamiento",
            name="clave",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
