# Generated by Django 4.2.10 on 2024-03-07 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sepomex", "0003_alter_estado_clave_alter_municipio_clave_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asentamiento",
            old_name="nombre",
            new_name="nombre_asentamiento",
        ),
        migrations.RenameField(
            model_name="estado",
            old_name="nombre",
            new_name="nombre_estado",
        ),
        migrations.RenameField(
            model_name="municipio",
            old_name="nombre",
            new_name="nombre_municipio",
        ),
        migrations.RenameField(
            model_name="tipoasentamiento",
            old_name="nombre",
            new_name="nombre_tipo_asentamiento",
        ),
    ]
