# Generated by Django 4.2.10 on 2024-03-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sepomex", "0004_rename_nombre_asentamiento_nombre_asentamiento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asentamiento",
            name="nombre_asentamiento",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="asentamiento",
            index=models.Index(
                fields=["municipio", "nombre_asentamiento", "codigo_postal"],
                name="asentamiento_cp_idx",
            ),
        ),
    ]
