# Generated by Django 4.2.10 on 2024-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sepomex", "0005_alter_asentamiento_nombre_asentamiento_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asentamiento",
            name="asentamiento_cp_idx",
        ),
        migrations.RenameField(
            model_name="asentamiento",
            old_name="nombre_asentamiento",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="estado",
            old_name="nombre_estado",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="municipio",
            old_name="nombre_municipio",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="tipoasentamiento",
            old_name="nombre_tipo_asentamiento",
            new_name="nombre",
        ),
        migrations.AddIndex(
            model_name="asentamiento",
            index=models.Index(
                fields=["municipio", "nombre", "codigo_postal"],
                name="asentamiento_cp_idx",
            ),
        ),
    ]
