# Generated by Django 4.2.10 on 2024-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sepomex", "0006_remove_asentamiento_asentamiento_cp_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estado",
            name="clave",
            field=models.CharField(default="333", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="estado",
            name="nombre",
            field=models.CharField(default="ERROR", max_length=250, unique=True),
        ),
    ]
